### ISSUE TITLE
Can't get new modded item from Hideout modded crafting

### ISSUE THREAD

**Issue by Randomizzatore** [justemutarkov/ServerMods#53]
[ERROR] [UNHANDLED][/client/game/profile/items/moving] request data: {
        "data": [
                {
                        "Action": "HideoutTakeProduction",
                        "recipeId": "gun_power_coin_workbench_craft_1",
                        "timestamp": 1586966198
                }
        ],
        "tm": 2,
        "reload": 1
}

The result is a gun_power_coin, a new item made by me.
It doesn't work with a modded item but it works with vanilla ones, I had another user try it and it didn't work, and Sorata told me it could be some missing script implementation

**Comment by KandaSoranyan** [comment]
I never said that it could me missing script implementation

**Comment by KandaSoranyan** [comment]
Is this now fixed ? @Randomizzatore

**Comment by Randomizzatore** [comment]
> Is this now fixed ? @Randomizzatore 

I haven't tried, I will try again today and give update

**Comment by InNoHurryToCode** [comment]
If anything, this is an issue for the server repo ;)
